### ISSUE TITLE
Typo in the User Manual pdf at Remix Controls

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#1]
"Start/Stop VLoopler" etc. should be "Start/Stop VLooper1".

**Comment by mdotstrange** [comment]
Is the typo on this page? Not sure where it is
[Screen cap of Remix page](https://i.imgur.com/V2fgshj.png)

**Comment by tonikone** [comment]
> Is the typo on this page? Not sure where it is
> [Screen cap of Remix page](https://i.imgur.com/V2fgshj.png)

That is the page, under heading Local Vlooper Controls. All items have an additional lower case L in them.

**Comment by mdotstrange** [comment]
Whoa good eye- my brain didn't even see those had to look 3 times- fixed now https://i.imgur.com/Aq1i5EB.png Thanks!
