### ISSUE TITLE
VLoopers: Stopping and playing back VLoopers produce KeyNotFoundErrors

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#100]
To reproduce:
1. Start recording to Vlooper
2. Stop recording
3. Play VLooper, Stop VLooper
4. Play VLooper again. KeyNotFoundException is often triggered.

Log:
[output_log_vloopers_KeyNotFoundException_on_play_stop.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5084464/output_log_vloopers_KeyNotFoundException_on_play_stop.txt)

**Comment by mdotstrange** [comment]
Added another null check- will include with next build-

**Comment by mdotstrange** [comment]
Is this still happening in the newest build?

**Comment by tonikone** [comment]
Yes. After 3. press F2 repeatedly, like a neurotic Pro Weirdo tester. You can do it. F2, F2, F2, etc.. KeyNotFoundException got ya!

Log:
[output_log_VLooper_KeyNotFoundException3.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5123714/output_log_VLooper_KeyNotFoundException3.txt)

**Comment by mdotstrange** [comment]
Tried it and got the error- added an extra null check and tested again pressed f2 as fast as I could while playing a clip and no error- thanks

**Comment by mdotstrange** [comment]
After the last changes and tests it seems this is going(crosses fingers) closing this- thanks!
