### ISSUE TITLE
CLARIFICATION: What does "Actor DNA" means?

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#104]
![CL00](https://user-images.githubusercontent.com/69782583/90456993-b0aa6d80-e0d0-11ea-97c2-192febd232c4.jpg)

The meaning of "Actor DNA" is unclear.

Also, the language is unclear here:
![CL00_A](https://user-images.githubusercontent.com/69782583/90457150-2d3d4c00-e0d1-11ea-943e-ff3800876dee.jpg)
![CL00_B](https://user-images.githubusercontent.com/69782583/90457154-2f9fa600-e0d1-11ea-9b93-e5900e25d0af.jpg)

It says I can upload the DNA, but I can only download the actor. I suppose both mean the same thing, but it's unclear.

**Comment by mdotstrange** [comment]
I'll change the descriptions to "upload actor" and "download actor" for clarification thanks-

**Comment by mdotstrange** [comment]
Just changed it so closing this- thanks
