### ISSUE TITLE
UI: Add sound feedback to volume sliders in scene edit screen

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#108]
This concerns "MIDI volume," "Music Volume," "Voice1 Volume," and I believe the slider below "MIDI" on the right corner, but I'm not sure what that does.

**Comment by mdotstrange** [comment]
Will add the sounds to all sliders- thanks

**Comment by mdotstrange** [comment]
Added sounds to all the menu sliders- thanks
