### ISSUE TITLE
RESPONSIVENESS: MIDI "play" button does nothing.

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#109]
![R02](https://user-images.githubusercontent.com/69782583/90458223-2fed7080-e0d4-11ea-9a31-8ee7ac215b0d.jpg)

When I click it, it plays no sound.

**Comment by mdotstrange** [comment]
If there isn't a midi file loaded nothing plays- the Gb.sf2 is the loaded soundFont- the new Ui makes this clearer so closing this- thanks!
