### ISSUE TITLE
Editor for adding voice to actor 1 turns into Editor for adding voice to actor 2 when pressing back button in audio file list editor

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#120]
Start with Scene Menu.
1. Press Toggle buddy actor
2. Press Add Voice to main Actor.
3. Choose playlist editor.
4. Download workshop files from steam or select files from hard disk.
5. Press back button (the leftmost arrow button) in the list editor.
6. Bug appears. The Add Voice to main Actor menu now shows settings for buddy actor voice. Sometimes visual buddy preview shows, sometimes it's empty.

**Comment by mdotstrange** [comment]
This should be fixed in the build I just added to Steam- beta 2.2

**Comment by mdotstrange** [comment]
Closing this- thanks!
