### ISSUE TITLE
Human FX: not all key commands work

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#122]
Older builds had more Human FX, like Gas and Puke. Now I can only launch Bleed (;) and Sweat (') for particle emitters. Spin (.) and Fall (,) work like before.

**Comment by mdotstrange** [comment]
Gas, Puke and Spit only work when a voice is active- they audio detect when a voice starts after being silent and that is when they fire- tested them with a voice and they were still working- can you test again with a voice to make sure its not an issue I'm not aware of?

**Comment by tonikone** [comment]
Ah, reciting Shakespeare clearly while puking! So bizarre..

Two issues:
1. Bleed and Sweat don't activate while sitting. I want to bleed while sitting, my legs are tired, maaaan!
2. This is for comedy timing perfectionists, consistency nuts and impatient testers/developers: There is no delay in launching Bleeding and Sweating, while others take a considerable time to take effect. For me, the first reaction to delay was to start spamming every HumanFX and then forgetting what was on and off. For beginners, consistent launch immediacy would take most of those reactions off the map.

**Comment by mdotstrange** [comment]
Ah ok- let me check and see why that isn't working

**Comment by mdotstrange** [comment]
Ok made all the fx happen when you press them- yeh this makes much more sense- closing this- thanks!
