### ISSUE TITLE
Character Editor preset button enhancement: Keep button highlighting on while manipulating actor controls.

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#125]
Let's say I want to edit preset five, and the final intention is to save back to 5. OK, load 5. Then I go and manipulate body parts. While I'm doing this, the highlighting of preset 5 button is gone and when I come to save my masterpiece, I've forgotten where I wanted to save. Dang. What was the place again? I don't want to touch the buttons now, fearing I delete some perfectly fine thing. Highlighting prevents mental bookkeeping.

Super advanced feature: Preview models without loading them by just hovering over Load Preset buttons.

**Comment by mdotstrange** [comment]
Just added this feature- thanks!

For the super advanced- the actor loading is using a lot of Instantiating and Destroying so I imagine loading/unloading actors that fast would cause freezes and weird hiccups due to race conditions with all the Coroutines I'm using for it- will explore it later when all the major bugs are worked out-

**Comment by mdotstrange** [comment]
Closing this- I'll open a new one just with a feature requested for the advanced one- thanks!

**Comment by tonikone** [comment]
> For the super advanced- the actor loading is using a lot of Instantiating and Destroying so I imagine loading/unloading actors that fast would cause freezes and weird hiccups due to race conditions with all the Coroutines I'm using for it- will explore it later when all the major bugs are worked out-

On hover entry, you could use a cooldown timer period, maybe needed on exit, too - to destroy item properly before loading in new stuff. Lot of fine tuning there, therefore later dev time frame is the best.
