### ISSUE TITLE
Flavor editor Close cross: Add white shadow/background for visibility enhancement

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#126]
Sometimes the black cross vanishes into background while doing various flavors. Contrasting lighter background for the cross prevents this.

**Comment by mdotstrange** [comment]
Updated the button to look like this https://i.imgur.com/fM2YZkX.png

Also I forgot to document it but I made it so Esc closes the "gameboy" looking menus that use this cross like you requested-

**Comment by mdotstrange** [comment]
Closing this- thanks!
