### ISSUE TITLE
Drive Scene: Buddy locked to grabbing the wheel on actor switch, Main actor falls through driver seat

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#141]
Buddy is locked tight, can't be reset.

Pics:

https://imgur.com/a/eaNmn5N

**Comment by mdotstrange** [comment]
You know I didn't test this one after adding the actor switching- will check it out now- thanks!

**Comment by mdotstrange** [comment]
I'm making it so only the initial main actors hands stay on the wheel even after a switch BUT both of them can use upper body animations.
