### ISSUE TITLE
Corrections and edits to Randos page in the manual

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#142]
I corrected spelling of Randos and AI first, then edited the whole page.

****
Randos

Rando is an AI chaos agent. Adding them to your scenes creates more madness. In the options menu, select which Randos you want active and the maximum number of them present in the scenes. Right-click somewhere in the scene to make Randos walk there. Some of them obey, some don't.

**Comment by mdotstrange** [comment]
Just added this- thanks!

**Comment by mdotstrange** [comment]
Just updated the manual here and on Steam thanks.
