### ISSUE TITLE
Tuurd Talk: Major crashes while cycling between tracking cameras

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#144]
I had crashes when switching between tracking cameras short after launching the scene. Cause could be cameras or something else. Produces a dialogue to open the log directory. Answering Yes closes the app, directory not opened.

Log from appdata:
[error.log](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5145054/error.log)

**Comment by mdotstrange** [comment]
Can you send the output log for this too asI don't know how to read/debug those system logs

**Comment by mdotstrange** [comment]
Did some googling on that crash and found this- don't know if its the issue without seeing the output log though "Finally people. I have been successful in fixing this issue. It was extremely simple: All I did was start the game in administrator mode, and now it works perfectly."

**Comment by mdotstrange** [comment]
Found this too "Hello! That usually happens when your anti-virus won't let you launch the game, please create an exception."

**Comment by tonikone** [comment]
Out of memory issue?

[output_log.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5145076/output_log.txt)

**Comment by mdotstrange** [comment]
Oh I see yeh- its the crowd eating up too much memory- have seen this before I need to optimize the crowd- how much RAM does your system have btw?

**Comment by mdotstrange** [comment]
I'll do some tweaks and optimizations for the crowds tomorrow- its crashed a few peoples PC's

**Comment by tonikone** [comment]
16 Gigs. After opening task manager, noticed you are making 32-bit builds. Those don't support memory over 4 Gigabytes, as far as I know.

**Comment by tonikone** [comment]
A leak?  The memory use starts growing after scene launch. Maybe some things are not released properly. Looks like it does not matter if one has system memory capacity past four Gigabytes. Go over it in NP and it is game over.

**Comment by mdotstrange** [comment]
Dude, great catch! I have been making 32 bit builds on accident 0_0 - I switched the build output to try and make a mac build weeks back and when I switched it back to windows I set it to 32 instead of 64 so yeh these crashes are most likely because of that- 9000 bonus tester points for you maaaaaaan- thanks!

**Comment by mdotstrange** [comment]
Updated the Steam build with a 64 bit version- thanks!

**Comment by mdotstrange** [comment]
Going to chalk this one up to the 32 bit builds you discovered- closing this- thanks!
