### ISSUE TITLE
Shift+F3 spawning with wrong rotation or excessive twitching.

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#15]
This seems to be limited to three specific bodies. The behaviour appears on every scene. Reloading the scene can correct the wrong rotations.

The images of the bodies:

https://imgur.com/a/CFmCl6t

**Comment by mdotstrange** [comment]
Are those the Null refs from issue #16?

Yeh that body(theres two like that with diff textures)... I imported those from some free 3d model site and yeh everytime it spawns its laying down so have to reset it to stand upright- I decided to leave it in- its extra funny when it spawns as a fashion model in the Fashcism scene as its floating like that ^_^

**Comment by mdotstrange** [comment]
Going to consider this a feature as it only happens with 3 bodies- use at your own risk ^_^ Closing this-
