### ISSUE TITLE
Drive Scene: Driver falls deep down into the seat

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#155]
Down to neck level. Tested with four models.

**Comment by mdotstrange** [comment]
What bodies are you getting this with? I just tried 6 different bodies and they all sat up like this
https://i.imgur.com/2ysTNS9.png

**Comment by tonikone** [comment]
https://imgur.com/a/J3l17Ja

After restart I can't replicate the most extreme behaviour no more. Looks like this is harder to pin down. Some shorter models (with suits) seem to affected more. Starting with a smaller character on scene start and switching to bigger body midflight with R+3 seems could cause unpredictable fluctuations, or vice versa. Of course, the taller actors need to placed down.. Hairy! The Composite Guy definitely is always under the wheel.

Also, there is a R+3 body switching anomaly: Hands don't go to wheel after the body switch. Enter+restart fixes this.

**Comment by mdotstrange** [comment]
Ok will look into this- was thinking of scaling the big bodies down a bit and the small ones up so there's less discrepancy in the sizes- what do you think?

**Comment by tonikone** [comment]
Yeah, I'll inspect it some more, too.

A NullRefException popped up:

[output_log_drive_seat_trouble.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5148933/output_log_drive_seat_trouble.txt)

**Comment by mdotstrange** [comment]
Ok added null checks for those- thanks

**Comment by tonikone** [comment]
Also noticed the tooltip persists and shows in the scene image after pressing Return for Remix/Scene editor intro page, hovering over icons and returning.

**Comment by tonikone** [comment]
Could not replicate the tooltip anomaly by switching to another scene. So that might maybe connected to popping up errors, or something else.

**Comment by tonikone** [comment]
The behavior seems to go this: Choosing tall actor initially and switching to shorter body midflight causes at least some shorter bodies to be pushed down. Restarting with shorter actor generally pushes actors upwards on R+3 body switches. Enter and Restart seem to correct things for R+3 selected bodies.

**Comment by mdotstrange** [comment]
Just fixed the hands on the wheel when switching bodies- so yeh when you switch bodies the hands stay on the wheel

**Comment by mdotstrange** [comment]
Made the cars roof higher and moved the seat position up- flipped through 20-30 bodies and they were all sitting in good place-

**Comment by mdotstrange** [comment]
Resolved in later builds-
