### ISSUE TITLE
Return menu tooltip persists in scene

### ISSUE THREAD

**Issue by mdotstrange** [mdotstrange/NightmarePuppeteerPublic#158]

**Comment by mdotstrange** [comment]
"Also noticed the tooltip persists and shows in the scene image after pressing Return for Remix/Scene editor intro page, hovering over icons and returning."

**Comment by tonikone** [comment]
I could not reproduce this after app restart. Could be tied to error popups, one of those just halted keyboard activity in Drive Scene. Might occur later, so let's watch out for this.

[output_log.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5149114/output_log.txt)

**Comment by mdotstrange** [comment]
Resolved in later builds-
