### ISSUE TITLE
Actor editor: Making props BIG causes hard to reset erratic motion when returning to Scene menu

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#159]
Tested with BIG hand props.

This behavior does not propagate into scenes, just the Scene menu is affected. Cramped scene spaces should be tested to make sure. 

Mitigations: Go back to editor, tune down prop size. Or start the scene.

**Comment by tonikone** [comment]
Elevator is not affected, so other scenes are unlikely to be affected by giant props.

**Comment by mdotstrange** [comment]
Just fixed this- problem was the prop colliders were interacting with the scene menu object colliders-
