### ISSUE TITLE
Da Club: Side rooms are inaccessible to actors

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#160]
Side rooms in Da Club can't be walked into. Marker 2 (raised up) is bit inaccurate, otherwise mitigating inaccessibility by markers works.

**Comment by mdotstrange** [comment]
Like these little rooms? https://i.imgur.com/lz5mQNc.png Seems there's small gaps in the navmesh that yeh would prevent walking in there- I'll add some navmeshLinks

**Comment by mdotstrange** [comment]
Made sure the navMesh is connected in all the side rooms now like so https://i.imgur.com/QZbJIoG.png

**Comment by mdotstrange** [comment]
Fixed in the latest build- thanks!
