### ISSUE TITLE
WindowsVideoMedia error on loading Bro Joban

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#168]
There is a suspect fixed tutorial video path in the log..

Logfile:
[output_log_bro_joban_error.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5163883/output_log_bro_joban_error.txt)

**Comment by tonikone** [comment]
Is this an Scene intro video that cannot be loaded?

**Comment by mdotstrange** [comment]
Oops! Will remove that path and submit a new build- thanks!

**Comment by mdotstrange** [comment]
I don't know what happened but looking into it 0_0

**Comment by mdotstrange** [comment]
Really weird as the error doesn't give a line of code that was trying to access it- just tried the scene after moving that video from my desktop and no errors- The only thing I can think of is the class that saves the video path for loading into the scenes didn't get initialized/blanked out properly.

**Comment by mdotstrange** [comment]
Have had this error come and go- is a weird windows error- leaving this open till I figure out why it happens-
