### ISSUE TITLE
FEATURE REQUEST: Implement PSX shader

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#176]
Implement [this shader](https://github.com/dsoft20/psx_retroshader). It's built for Unity.

**Comment by mdotstrange** [comment]
Checking it out now, thanks- if I can, I'll add it as a new flavor to apply to heads/bodies

**Comment by mdotstrange** [comment]
Here is a body and head with the PSX shader- its pretty subtle and would only apply to the actors and not the scene https://i.imgur.com/kj8ozhC.png  Still something you want? I would replace one of the cell shaders with it.

**Comment by mdotstrange** [comment]
I tried it on some other models- its an a subtle but interesting look- will be in the next build-
