### ISSUE TITLE
Vlooper2 does not work

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#2]
Two issues with VLoopers:

Vlooper2 does not seem to work.

Vlooper1 works, but Alt + F4 quits the application in windowed and fullscreen mode. This Windows shortcut can't be changed. Looks like registry poking does not help, and I can't recommend such actions to normal human users.

**Comment by mdotstrange** [comment]
Plooper 2 starts was never called so fixed that, thank you + will change keyboard shortcuts- What keys do you think I should put the Vlooper controls on- SHIFT + Fkeys?

**Comment by mdotstrange** [comment]
Fixed Vlooper 2 and remapped the Keys from both Vloopers- they now use F1-F7 keys
