### ISSUE TITLE
Funny Ha Ha: Another actor who borks out on spawning with Shift+F3

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#20]
Uncontrollable superfast twitching, Shift+R does not seem to help. This one disappered from stage while I was writing this. Was found outside the stage, lying stuck to the floor. Responds to click to move action, but stays stuck otherwise.

Some actors do fast "corrective movements" before settling down on the scene after spawn. These might have something to do with erratic behaviours.

See image:

https://imgur.com/a/nYXr1VX

**Comment by mdotstrange** [comment]
Yeah the Pizza body is cursed haha- it does all kinds of wacky stuff- I don't what is going on with its skeleton/ragdoll 0_0 Decided to leave it in as a wacky chaotic vibrating body

**Comment by mdotstrange** [comment]
Pizza lady BORKING is a feature- closing this ^_^
