### ISSUE TITLE
Loaded audio playlist items do not preview/play after app exit and relaunch

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#203]
Mitigation: The playlist items start playing again after visiting the playlist page and relaunching the scene. The visiting seems to refresh the playlist item text lines.

Getting every scene setting saved and loaded on app entry would be nice. Less gruntwork to continue work on scenes. This could be expanded into scene wide preset system to cater for different user groups working on different scenes, for example. Might help in generating automated sequential algorithmic scenes through direct manipulation of files. In general, semi-automatic scene, asset and actor management based on ticking boxes and changing variables in a separate, file generating app/webapp would lift a portion of management logic out of the runtime NP side and would kickstart new collaboration workflows, both human and robot/AI.

**Comment by mdotstrange** [comment]
"Getting every scene setting saved and loaded on app entry would be nice. " I agree and that is really easy to do- will add that! Thanks

**Comment by mdotstrange** [comment]
I tried to reproduce the Playlist error- I recorded two clips into the Audio Recorder/Playlist- I then quit then reloaded and they were in the playlist on reload- Can you tell me how to reproduce the issue? Thanks

**Comment by tonikone** [comment]
I did not do recording, just added items from HD to list. Then everyhing is ok. But when I exit the app and come back, toggle tabbing on and launch the scene (without visiting playlist editor), tabbing playback does not work. I have to visit the the playlist editor without doing nothing there and launch the scene again.

**Comment by mdotstrange** [comment]
Ok thanks I'll check with file loading

**Comment by mdotstrange** [comment]
Oh I see what the issue is- the files are loaded as I just tested that but yes only once you visit the playlist panel- i'll fix this- thanks!

**Comment by mdotstrange** [comment]
Just fixed this- thanks
