### ISSUE TITLE
Feature request: Add popcorn particle throwing to H4KLR 3d Feedback

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#23]
This classic is a must have.

Throwing coins - "Take my money". That is part of stage tradions in some parts of the world. Throwing flowers for romantic moments and Auteur adoration would be cool. 

H4KLR 3d Feedback is exciting. So many possibilities. Could the commands be chained for some kind of limited scripting, with basic wait states between actions? Potential for malice is great but rewards are plenty.

Some sort of filtered sets of H4KLR actions would be great. Some productions might not want popcorn showers all the time. Custom "Show stream session H4KLE actions" Twitch command?

**Comment by mdotstrange** [comment]
Ah great ideas! I'll add the coins/flowers/popcorn now- can you give me some examples of scripted actions?  In the latest build these are the HkLR/Twitch options [here](https://i.imgur.com/6AoBviw.png)

**Comment by mdotstrange** [comment]
Added Coins/Flowers/Popcorn and updated the manual + controls.md here reflecting that

**Comment by tonikone** [comment]
> Ah great ideas! I'll add the coins/flowers/popcorn now- can you give me some examples of scripted actions? In the latest build these are the HkLR/Twitch options [here](https://i.imgur.com/6AoBviw.png)

Since currently there is no way to switch DNA on the fly, it could be a candidate. Offline scripting is a must.  Hiding and unhiding props for faking getting champaign from the fridge, for example. Positioning of prop nulls to scene with level editor, hide/unhide items attached to those nulls. Dynamically loading body props from fixed directories Props1, Props2, Props3 - or specific body part directory, like Actor1LeftHand, Actor1RightHand etc. Assigning HkLR script to a keyboard shortcut. Accessing scripts line by line, maybe go back and forth, set up loop points for sections of scripts, jump points, algo madness! Wildcards for loading directory contents. Loading scripts in scripts, accessing random lines of script. Reassigning keystrokes, that's a good one. Loading keyboard shortcut setups, maybe for specific operators, that's a good one.  Bigger lists of on-scene cast and rotating the current actor to control. Assign control of specific actors to specific Twitch users, that is an excellent one. Maybe expand the camera action palette, like bringing specific cameras to specific position in relation to actor on the scene, then save and load relation with commands. Tweening between two camera locations: Assign the camera pos/rot to Cam1Pos1, move the camera, assign the camera position to Cam1Pos2, fire a tween from script. Launching a scriptable popup with option buttons, radio buttons, sliders and so on, that would be ace for people who are afraid to write or read code. Setting up waypoints for walks, loading sets of facial expressions when those surface, setting up punch-in effects for sizes for eyes, props, flavors. Dynamic loading of different audio volume setups, applying more realtime effects to audio (eq, reverb), writing credit rolls, switching textures on billboards, switching paints on the characters for blushes, loading items from trusted servers, switching between web service integrations on the fly, sign in and out of services.. Expand, expand, expand.. I'm stopping now.

Accessing scripts would be would be sooo nice. One could have text editor on the side and punch in needed stuff on the spot, test right away. Essential for peeps who like to build systems.

BTW, Hasu makes a programmable USB keyboard dongle which allows use of multiple keyboards with different single stroke shortcuts per dongle. https://www.1upkeyboards.com/shop/controllers/usb-to-usb-converter/

**Comment by mdotstrange** [comment]
Thanks for all the ideas! Going to look into some I can do- The popcorn etc has been added so closing this-
