### ISSUE TITLE
Recommend HUD

### ISSUE THREAD

**Issue by joshmorales2** [mdotstrange/NightmarePuppeteerPublic#238]
Recommend hud display which you can also hide.
Would show current animation key active. Character active
Camera active ect. Maybe 3 modes. On screen, off screen (like so you can adjust obs) and hidden.
If something is there forgive me. I have no time lol.

**Comment by mdotstrange** [comment]
Good ideas- thank you for posting them- I'll look into this and see what I can do- thanks.

**Comment by mdotstrange** [comment]
Added a HUD to the latest Beta https://i.imgur.com/XJzuVpo.png
