### ISSUE TITLE
Restart scene media tab to talk 

### ISSUE THREAD

**Issue by joshmorales2** [mdotstrange/NightmarePuppeteerPublic#255]
When clicking restart scene media. Tab to talk autostarts. Is this a feature or a bug.
Then I usually have to restart full scene and not just the media. Cuz I'm just trying to get the music to restart not the tab to talk if ya know what I mean. 

Thx.

**Comment by joshmorales2** [comment]
Realized middle click tab stops tab to talk. So wll use that in mean time.

**Comment by mdotstrange** [comment]
I can add a restart music button? that work?

**Comment by mdotstrange** [comment]
Added a restart music button- will be in next build-
