### ISSUE TITLE
Lousy global axis

### ISSUE THREAD

**Issue by joshmorales2** [mdotstrange/NightmarePuppeteerPublic#256]
Seems like spacebar access local axis. Makinblg it hard to move things laterally when rotated. Can you add shortcuts for global axis manipulate?
Perhaps spacebar plus s d and f?

**Comment by mdotstrange** [comment]
I believe there already is a toggle I just didn't document it- I'll will test then add the other keyboard shortcuts to the manual-

**Comment by mdotstrange** [comment]
Yeh X is the toggle for local/world space- here's all the shortcuts for the level editor transform controls https://i.imgur.com/6NV5PwZ.png
