### ISSUE TITLE
Save load

### ISSUE THREAD

**Issue by joshmorales2** [mdotstrange/NightmarePuppeteerPublic#257]
Clarify save spots and if they are taken already. I think its supposed to be highlighted but I'm not certain it's working correct for me. Alslways super scared to save. 
Popup are you sure you want to overwrite.
Load thumbnails

**Comment by mdotstrange** [comment]
Yeh I believe it is bugged- I will fix it next update

**Comment by mdotstrange** [comment]
Made it so save slots that are occupied are darker- loading icons and the other will have to come later- faded slots help though- will be in next build

**Comment by mdotstrange** [comment]
Just fixed some bugs in this- should be good now

**Comment by Jolsh2** [comment]
Any chance for this:

When hover over a save or load slot. A pop-up thumbnail shows what currently exists in that slot? MKes it easier for save over. I imagine this will be useful for Clay items or puppets if we start pumping thoes out.
