### ISSUE TITLE
Moving Puppet's heads in the car.

### ISSUE THREAD

**Issue by JacktheRipper-glitch** [mdotstrange/NightmarePuppeteerPublic#261]
I am a little confused by this, I kept trying to but it seems like you can't move their heads at all, if that's the case would it be alright to change it so you can?

**Comment by mdotstrange** [comment]
I'll look into this as you should be able to- thanks!

**Comment by JacktheRipper-glitch** [comment]
> I'll look into this as you should be able to- thanks!

Yaaaaaay. Jackie gun sleep now.

**Comment by mdotstrange** [comment]
Fixed in Beta 1.3.2
