### ISSUE TITLE
Puppets as npc

### ISSUE THREAD

**Issue by KarenMaboob** [mdotstrange/NightmarePuppeteerPublic#262]
Possible to put puppets that are in your save slots as a npc? Forsee need to have some in backgrund. Could just do multiple runs and cut in video editor if too much trouble.

**Comment by mdotstrange** [comment]
Thats an interesting idea- so just have them do the same random actions etc as the normal NPC's? Except you place them with the level editor or something? If you explain how you want to use this- will help me come up with an idea to implement it- thanks-

**Comment by KarenMaboob** [comment]
Like I would want to show one 'team' of 5 character vs another team of 5 or so.
So I would want them standing. They can bob or whatever. But I would probably use them as items. You mentioned that they could also just random walk that would be interesting but I haven't planned on having them random walk yet cuz I'll set up the scene and if they move out of position I'll be pissed lol.

**Comment by mdotstrange** [comment]
Ok- this will take me a little time to figure out how to do it right.

**Comment by KarenMaboob** [comment]
Thanks. Really tho no rush. Ur doing this all for free. So thanks!

**Comment by SameSkeletonDifferentCloset** [comment]
Yeah I wish I could donate money. I get so happy when there's updates but I feel like he's really going out of his way and taking time off from more important projects. As much as I put out videos it's too bad I don't get a penny for each one then I could send a fat piggy bank to m dot.

**Comment by mdotstrange** [comment]
Ah don't worry bout it dudes- I'm dedicating weekends to game dev- updating NP and working on another project + watching UFC at the same time haha- making small changes to NP is actually fun.

**Comment by mdotstrange** [comment]
And when I say it will take me time- that prob means like 15 minutes vs. 5 minutes haha

**Comment by SameSkeletonDifferentCloset** [comment]
Hey thanks for the kindness and passion. When I first saw you on video I thought you had a good strong build. So I'm not surprised you'd watch UFC. I was just thinking how Jolsh may add that to his/her long list of nicknames. Then I thought a wrestling ring or something like that would be neat!

**Comment by SameSkeletonDifferentCloset** [comment]
> And when I say it will take me time- that prob means like 15 minutes vs. 5 minutes haha

Oh I was thinking a week or week in a half at the latest.

**Comment by mdotstrange** [comment]
Programming is like a puzzle to be solved- so each feature request is a new puzzle to solve- it can be fun to do.

**Comment by mdotstrange** [comment]
I figured out a way to do this- the NPC's would only show up in the level editor- it would add all your saved actors to the level editor- they would work fine but if you say added them to a custom level you added to workshop they wouldn't be saved with the custom level- that still cool?

**Comment by SameSkeletonDifferentCloset** [comment]
Damn I'm replying to this too late. That's fine with me but then again Jolsh should chime in since he first rang that bell.

**Comment by mdotstrange** [comment]
This has been added to the latest beta build_ I will upload soon
