### ISSUE TITLE
Click thru menu

### ISSUE THREAD

**Issue by joshmorales2** [mdotstrange/NightmarePuppeteerPublic#266]
See if you can recreate.
I pull open the menu and hit the restart music button and it clicks thru and controls the character. Then I scramble to get the character back to where I want him/her/ze/cow/muffin

**Comment by mdotstrange** [comment]
Yeh that is a bug- I will fix that in the next update- thanks!

**Comment by mdotstrange** [comment]
Ok just fixed this- will be in next update

**Comment by mdotstrange** [comment]
Update with this fix is live now beta branch v 1.4
