### ISSUE TITLE
Editor item not loading

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#280]
In the testy beta as of today. Wiggle Green invisible Npcs and pricing
Lousy editor items not loading. 
Tried uninstall reinstall already.

**Comment by KarenMaboob** [comment]
![Uploading 20201214_210107.jpg…]()

**Comment by Jolsh2** [comment]
It's was my AOC characters body. It's the female large breastfed body with black and white. Kinda like a jail clown. The editor doesn't like it. Can you verify. The character was in a save slot and I believe that's what messed it up

**Comment by mdotstrange** [comment]
Fixed in latest build
