### ISSUE TITLE
Green Screen Scene coming apart at the Sceams?

### ISSUE THREAD

**Issue by SameSkeletonDifferentCloset** [mdotstrange/NightmarePuppeteerPublic#289]
I replicated it. Happened every time. I didn't realize it was a portal that has cloned Mdot. Oh no's! 

https://youtu.be/UHdgW48WIC0

**Comment by mdotstrange** [comment]
I think this one has a navmesh bug where yeh they walk through the walls- I'll fix this in the next update- thanks!

**Comment by mdotstrange** [comment]
Fixed in upcoming new beta build.
