### ISSUE TITLE
Character editor: Prop loc/rot/scale doesn't get saved to DNA slots

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#29]
To reproduce, manipulate prop loc/rot/scal 3D widgets e and save variations into different DNA slots. Trying to load DNAs the settings revert to values loaded on app startup. Exiting the editor without saving DNA carries the latest manipulations correctly into the scene, back to main menu and into the editor. On app restart the latest 3D widget manipulations are again reverted to some earlier state (in my case scaling had sticked at some point, but that might have been slider scaling), which are not related to any of the saved DNA settings.

Scaling with 3D widget manipulators does not get reflected in prop scaling sliders, so I suspect 3D manipulation use is ignored by the save to DNA functionality.

**Comment by mdotstrange** [comment]
Ah good catch- I forgot to save the changes after adding the menu camera + transform manipulation- will look into this

**Comment by mdotstrange** [comment]
Actually only scaled is saved in the Dna as you couldn't move/'rotate them before- Updating the dna class to also store position/rotation

**Comment by mdotstrange** [comment]
Ok wrote some code to fix this- just tested it and works now- will leave open for more testing- next build will have this fx thats Beta_3

**Comment by mdotstrange** [comment]
tested in new build- works- closing this- thanks!
