### ISSUE TITLE
Suggest option for turning off glare in empty scene

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#290]
The empty scene leaves glare on photos I place on the ground. For the last Diablo one I needed to have a huge green screen but the glare made it light green in some areas and was messing up when using that chroma option in shotcut. If the glare was able to be turned off I think the puppet wouldn't be as so invisible if the green screen would be a simple color. I tried ' blocking out the sun with an object but didn't work. Just a suggestion. Originally I was just going to have the Diablo town picture on the floor but the green screen was way easier to do while scrollg the jpeg in the background instead of manually moving puppet. Anyways just a suggestion. The green screen levels were a little to small for me for this specific instance. Maybe I could of made it work... Anyways a vinallia level without glare might be useful. But certainly if you get a chance not a priority for sure!

**Comment by Jolsh2** [comment]
![Screenshot_20210107-113514_Twitch](https://user-images.githubusercontent.com/71854487/103918218-82a7e300-50dc-11eb-83d0-14212ff2ac24.jpg)

**Comment by mdotstrange** [comment]
This could be a tricky one as the glare is from the materials themselves- I'll see what I can do- thanks!

**Comment by mdotstrange** [comment]
So I made the KeyMe green screen level about 4x bigger- I'll look at the green screen objects and see if I can remove their specularity.

**Comment by mdotstrange** [comment]
I disabled the glare on the image holders.
