### ISSUE TITLE
Closet scene

### ISSUE THREAD

**Issue by SameSkeletonDifferentCloset** [mdotstrange/NightmarePuppeteerPublic#291]
Better yet a coffin I can lie in. 

Michael, please at least have the decency to tell me to go fuck myself instead of just ignoring me so I can leave you the hell alone. Don't just act as if there was nothing lost here. Jack was forgiven hours later. Me? A big enough threat and hardy meal to keep you going? Let's be adults. 

Thank you.

**Comment by mdotstrange** [comment]
> Better yet a coffin I can lie in.
> 
> Michael, please at least have the decency to tell me to go fuck myself instead of just ignoring me so I can leave you the hell alone. Don't just act as if there was nothing lost here. Jack was forgiven hours later. Me? A big enough threat and hardy meal to keep you going? Let's be adults.
> 
> Thank you.

These issue pages are for bug reports and feature requests only.
