### ISSUE TITLE
Futbol level 

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#293]
I think something is terribly terribly terribly wrong. Just terribly terribly terribly terribly terribly wrong.

Check out scene editor with this level. Everything was flat and was placed in a Y level higher than the plane of the field. Jolsh had a hard time moving too! Haha

https://youtu.be/tp-oZ0gf-bs

**Comment by mdotstrange** [comment]
Thanks for letting me know- I think I know why its doing this- will fix today- thanks!

**Comment by mdotstrange** [comment]
Ok just fixed this- will update beta today

**Comment by Jolsh2** [comment]
Does balls have friction. Kinda hard to run after a ball which does not slow down.

**Comment by mdotstrange** [comment]
I'll add some angular friction I think its called to slow the rotations.

**Comment by mdotstrange** [comment]
Made it so the balls roll slower/will slow down in next update
