### ISSUE TITLE
Cameras 'tied together' 

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#294]
Recorded issue. 

https://youtu.be/0PMgT-LnvwU

**Comment by mdotstrange** [comment]
I was getting this too in the editor when testing but I thought I fixed it- thanks for letting me know- will fix today-

**Comment by mdotstrange** [comment]
Ok pretty sure I fixed this- what was happening is-

On game start NP looks to see if you have a save file(stores all camera data etc) if a save file is present it loads it into memory and uses it to set camera when you load a scene-

Problem was- if I added NEW scenes they do not exist in the saved file if a user had one- so there was no camera data to load-

At game start all the defaultCameraData is loaded into memory too- thats what is used when you click reset cameras(if the scene exists in your save file haha)

So now if a saved file is loaded I check to make sure there aren't scenes in the default data that are not in the saved one- if there are new ones I add them to the previous save file etc

But yeh after next update let me know if this is still a thing- thanks!

**Comment by mdotstrange** [comment]
Ok fix for this and the futbol issue are in new beta build on Steam now- 

btw I changed the way saved cameras are loaded so if there's any weirdness let me know- thanks!
