### ISSUE TITLE
Puppet DL from workshop affects both puppets

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#296]
When downloading and applying to puppet 1 puppet 2 is altered except for the items. Also vice versa. Updating 2 affects 1.

**Comment by mdotstrange** [comment]
I think I've seen this before, will check this out for the next update- thanks.

**Comment by mdotstrange** [comment]
Ok I think this one is fixed- fix will be in next update-
