### ISSUE TITLE
Saved Configuration?

### ISSUE THREAD

**Issue by SameSkeletonDifferentCloset** [mdotstrange/NightmarePuppeteerPublic#304]
There's a few things I do after launching NP like turning ambience and sound fx down, voice volume up, click derp on, no people in scenes, etc. Anyway to have an option to save this? 

By the way, was there an update earlier? If so, what's the details?

Thank you.

**Comment by mdotstrange** [comment]
It should be saving those settings- sounds like a bug, I'll check it out- thanks.

**Comment by SameSkeletonDifferentCloset** [comment]
Sorry. I meant saved for each time you launch it.

**Comment by mdotstrange** [comment]
When you quit then relaunch NP it should be saving those settings so they remain the same on relaunching it- looking at the code now-

**Comment by mdotstrange** [comment]
Looking at the code- it looks like it is saving derp eyes but not any of the volume settings- its also not saving the no people settings so I'll add that-

**Comment by SameSkeletonDifferentCloset** [comment]
Oh that's cool. I didn't know you intended those things to also be saved. Thank you!

**Comment by mdotstrange** [comment]
Ok everything should be saving in the next updated version-

**Comment by SameSkeletonDifferentCloset** [comment]
Thanks for the quality of life feature.
