### ISSUE TITLE
Deactivating Youtubrrr leaves Youtubrrr audio playing on re-entering the scene through main menu

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#32]
Noticed while testing Court scene. Current behaviour: Turn on Tubbrrr, play the scene. Exit to main menu, go to play settings and uncheck Youtubrrr, I pressed the cross button too (Cross not in pdf manual. What does it do?). The miniwindow is gone, but Tubrrr audio sticks.

**Comment by mdotstrange** [comment]
Youtuber wasn't being destroyed on reset but now they are and added button to manual- it now deletes a youtuber if they persist- closing this- thanks!
