### ISSUE TITLE
Endless spinning can't reset ragdoll

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#346]
Will link vid

**Comment by Jolsh2** [comment]
https://youtu.be/2KF7kNTT52s

**Comment by Jolsh2** [comment]
I think something is wrong with obs. Hmm. .....

**Comment by mdotstrange** [comment]
Hmm this is prob an NP error locking things up- Its not a "Dev build" so it won't show you the errors- if you go to this folder under your user name
https://i.imgur.com/DUq2vN9.png

Send me the "Player" text file and I'll be able to see any errors in there

**Comment by mdotstrange** [comment]
Fixed with OBS issue fix
