### ISSUE TITLE
Can't click x and close the clay help menu

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#347]

**Comment by Jolsh2** [comment]
The sound of clicking happens but doesn't close the menu.

**Comment by mdotstrange** [comment]
There must be an error that is stopping things- can you send me the "Player" file so I can check it out?
https://i.imgur.com/DUq2vN9.png

**Comment by mdotstrange** [comment]
Just got this issue myself- will fix now

**Comment by mdotstrange** [comment]
Added a new build just now- let me know if you still have this issue- thanks

**Comment by mdotstrange** [comment]
Fixed in new build
