### ISSUE TITLE
OBS

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#348]
could be my machine or resources, but maybe there is a reason that OBS does not record the window correctly. I just redownloaded the Beta version and OBS works with the window capture source. but does not work for me in the testy version. if i get more idea. will let you know.

**Comment by mdotstrange** [comment]
Hmm it might have to do with Unity removing the resolution/quality window- with previous versions of NP what res/quality/window setting did you choose? Did you do full screen with the old one too? Since you can't change NP"s resolution right now maybe its too high? Don't know-

**Comment by SameSkeletonDifferentCloset** [comment]
I had the same issue. I live-streamed trying out the clay on YouTube. I may have have not done it right but OBS remained on top of NP and there was no audio. It's good no one saw it. Hah.

**Comment by mdotstrange** [comment]
I added a new build with a Quality setting dropdown- let me know if setting it to low quality changes anything-

**Comment by mdotstrange** [comment]
I figured out what caused the OBS issue + character flipping- "run in background" got disabled so if you switched away from NP, NP freezes this also caused the actors to flip out- fix will be in next build
