### ISSUE TITLE
Some rando protest signs are glitchy

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#35]
Protest signs seem to be constructed of two single sided polygons. Some work properly, some not. The ones not working have parts crossing/rotating/overlapping each other, cutting parts of sign images away.

**Comment by mdotstrange** [comment]
Is this when using the crazy flavors that distort the mesh? If so I can prevent the signs from being affected by the "flavors"

**Comment by mdotstrange** [comment]
I made it so the flavor changes will ignore the signs so they should always be visible/not glitchy

**Comment by tonikone** [comment]
> Is this when using the crazy flavors that distort the mesh? If so I can prevent the signs from being affected by the "flavors"

Oh yeah, flavors do it definitely. The other glitch is the crossing movement of the protest sign sides which can cause masking. A pic:

https://imgur.com/a/Q5k3B9h

**Comment by mdotstrange** [comment]
Ok fixed the flavor bug- hmm don't know if I can do anything about the crossing unless I made them physical objects with Rigidbodies but might mess with the ragdoll etc- will see what I can do

**Comment by tonikone** [comment]
Would making a thin box and applying texture UV to both sides help?

**Comment by mdotstrange** [comment]
hard to tell in the img- is that one sign that is intersecting with itself? Or two signs intersecting?

**Comment by mdotstrange** [comment]
Flavors no longer affect the signs- closing this
