### ISSUE TITLE
Teeth editor: Some model's teeth cannot be scaled

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#38]
See pictures:

https://imgur.com/a/Sq3nEfF

Couple models have no teeth. One's teeth is obstructed by moustache (my man Nietzsche, poor guy..), the other one's mouth is quite small (Pic: https://imgur.com/a/5HD41VS ). Excluding teeth on these models might have been optimization.

**Comment by mdotstrange** [comment]
Checking this one out- it seems to me like its not the teeth that are the problem its the heads- some heads don't allow any teeth to be scaled

**Comment by mdotstrange** [comment]
Problem was with the heads- fixed this- thanks!
