### ISSUE TITLE
Loading additional sounds into the list causes index out of range error

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#4]
Coming back to application after closing, loading additional sounds into the list causes index out of range error.

Workaround: Clearing the list and reloading files does not give errors.

**Comment by mdotstrange** [comment]
When you say "loading additional sounds" do you mean by recording them or by using the "Load file" button?

**Comment by mdotstrange** [comment]
Also if you have the debug_log for that would be really useful- thanks!

**Comment by tonikone** [comment]
This might have been after a swipe on the record button and not appending the file to list. Can't reproduce this with file loading only.

Quite often after quitting the game and relaunching, tabbing the files don't play them. 

[output_log_tab_not_playing_audio_files.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5023214/output_log_tab_not_playing_audio_files.txt)

**Comment by tonikone** [comment]
> Also if you have the debug_log for that would be really useful- thanks!

Here it is. I'm glad I saved it because I can't reproduce this by file loading only. 

[output_log_sound_list_loadin_index_out_of_range.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5023231/output_log_sound_list_loadin_index_out_of_range.txt)

**Comment by tonikone** [comment]
I did this: Clear appdata files, start from clean slate. Load files to audio playlist. Start Fynny Ha Ha scene, exit scene to main menu, exit application. Start application again, start Funny Ha Ha scene, tab to launch audio files on the list. Nothing happens. Then, just _visit_ the audio playlist without making changes to the list. Start Funny Ha Ha again. Tab to play audio files. They play back normally.

Log:

[output_log_tab_not_playing_audio_files_after_erasing-configs.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5023513/output_log_tab_not_playing_audio_files_after_erasing-configs.txt)

**Comment by mdotstrange** [comment]
Thanks for the details + logs- So I looked through the log files- the error I found was an "Out of Range exception" from the Looks menu flavor preset bug  issue #3 - I didn't see any from the Audio Playlist- seems it could be the Looks/Flavor menu preset error?- I will send a new build tonight which you can test the audio again- thanks- leaving this open
