### ISSUE TITLE
Actor editor: Awkward hand prop rotations

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#40]
The editor hand prop rotations have changed and sometimes look awkward.

See picture:
https://imgur.com/a/sDFa8Wf

[Edit] Crotch prop rotations look OK. Flag hangs correctly.

**Comment by mdotstrange** [comment]
Before I added the manual p/s/r changes you couldn't change the pos/rot so I wasn't saving/storing this- now it is-- I'll check this one out tomorrow-

**Comment by mdotstrange** [comment]
Do you think this is a body specific thing? I had to manually set all the hand prop holder positions on the bodies to get them right weeks back and I'm sure I missed a few of them-

**Comment by mdotstrange** [comment]
Manually fixed all the hand prop holder positions- closing this- thanks!

**Comment by tonikone** [comment]
> Manually fixed all the hand prop holder positions- closing this- thanks!

Still one to go, the you are done. The invisipants body has a crooked crotch prop. Picture:

https://imgur.com/a/8dIKXVf

Others seems to be OK.

Cyber bodies have reverse direction crotch props, but that's the outcome of hard-ass cyber lifestyle, right?
