### ISSUE TITLE
Mouth/Head Prop editor: The Murican flag prop glitches when moving scale slider

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#41]
There is some polygon weirdness at the base of the pole and pole swivels oddly when moving slider. The base null is maybe in the wrong place, or moves itself for some reason. Noticed this first on mouth prop editor. Then behaviour propagated to other body parts. Test all body positions. Only flag affected so far.

**Comment by mdotstrange** [comment]
Yeh saw this one too- The flag has joints in it- prob something to do with those- I'll take a look- thanks!

**Comment by mdotstrange** [comment]
Its a feature ^_^
