### ISSUE TITLE
Actor prop editor: Muzzle flash glitch when activating 3D manipulation widget

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#42]
The effect glitch stops when moving to next prop or when exiting the actor editor. All muzzle weapons seem to be affected.

See picture:

https://imgur.com/a/dRNFZsg

**Comment by tonikone** [comment]
Flashlight is affected too, so all light emitting objects might be also be affected.

**Comment by mdotstrange** [comment]
This glitch only happens when its selected like this eh? https://i.imgur.com/psn7p8X.png

When you deselect it goes back to normal yeh? https://i.imgur.com/3jM3Iiw.png

**Comment by tonikone** [comment]
> This glitch only happens when its selected like this eh? https://i.imgur.com/psn7p8X.png
> 
> When you deselect it goes back to normal yeh? https://i.imgur.com/3jM3Iiw.png

Yes. Are these all attached with sprite particle effects or specific shaders? I Notice familiar looking blackened sprite cards moving when looking at smoke from a cigarettes. Items affected by this phenomenon seem also be absent from lever editor menus.

**Comment by mdotstrange** [comment]
Yeh seems to be an issue with the particle systems- they are present in the level editor icons- they are just blank icons or they render the wrong icons- don't know why? 0_0

**Comment by mdotstrange** [comment]
Its a feature ^_^
