### ISSUE TITLE
Manual: Run to position works only when backspace is pressed down first, not as stated in the manual (left click + backspace)

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#421]
I'd correct "Left click somewhere + Backspace" to "Backspace + Left click somewhere"

**Comment by mdotstrange** [comment]
Will check and see if I can make it work properly or will change the manual- thanks

**Comment by mdotstrange** [comment]
Changed manual to match behavior thanks
