### ISSUE TITLE
Command Console: Pressing Enter to submit command takes user to scene editor settings menu

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#423]
I liked to enter my commands with Enter key instead of lifting my hand for mouse every time I want to submit a command. Whad's going on here maaaaaan?

Manual says shift+esc should toggle the console. While working in scenes, I can't get out of NP Console using this combo. However, in main menu this works. Is there a conflict in keyboard command mappings involving esc key? Getting shift+esc console close to work would mitigate the mouse-ray-through-buttons-to-scene problem.

**Comment by mdotstrange** [comment]
This was a bug in a build that was live for a day or two- give it a try with a new build and I'll check the return key issue- thanks

**Comment by mdotstrange** [comment]
I'll fix the return thing now- yeh thats annoying haha

**Comment by mdotstrange** [comment]
This is fixed in latest Steam build thanks
