### ISSUE TITLE
Pressing Enter key in active scene does not open Scene Editor menu

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#424]
Console command entry by enter key now works, but entry to Scene Editor menu with Enter key is now barred while working in active scene.

**Comment by mdotstrange** [comment]
Thanks for the heads up maaaaan- just fixed this and will update Steam build- I was checking to see if the Console script was enabled instead of whether the Console window was active 0_0

**Comment by mdotstrange** [comment]
Update now on Steam
