### ISSUE TITLE
Prop selectors: Prop changes to new one when selecting prop with spacebar+click to start editing with 3D widgets

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#43]
To replicate: Select new prop with arrows. Press spacebar+click to edit prop with 3D widgets. The prop changes to new one according to last selected direction arrow.

Mitigation: Move the scale slider before pressing spacebar+click.

**Comment by mdotstrange** [comment]
I was getting this too- I should make it so once you use Spacebar select it deselects any active button-

**Comment by mdotstrange** [comment]
The Spacebar and Enter/return key were set as the default "Submit" buttons- removed them as thats never used for anything intentional and now the issue is gone- thanks!
