### ISSUE TITLE
Small Pharma and Combini are blank and unresponsive.

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#433]
After loading these scenes everything is blueish black and there is no key response. Requires hard Stop from Steam menu.

**Comment by tonikone** [comment]
And More News, Dark Cabin are blank and unresponsive too.

**Comment by tonikone** [comment]
These seem to be consecutive scenes. Is that a hint?

**Comment by Somebody123cool** [comment]
Yes, I have also encountered this same issue and noticed that this usually happens when removing people/toilet options are enabled from the scene option menu.

**Comment by mdotstrange** [comment]
Will check this out today- thank you!

**Comment by mdotstrange** [comment]
I wasn't able to reproduce it which makes me think its a game save issue- try deleting the SavedNightmare file here and trying the scene again https://i.imgur.com/U0HV88U.png

**Comment by mdotstrange** [comment]
> Yes, I have also encountered this same issue and noticed that this usually happens when removing people/toilet options are enabled from the scene option menu.

Putting on my plumber hat now and checking the pipes.....

**Comment by mdotstrange** [comment]
> After loading these scenes everything is blueish black and there is no key response. Requires hard Stop from Steam menu.

I wasn't able to reproduce it which makes me think its a game save issue- try deleting the **"SavedNightmare"** file here and trying the scene again https://i.imgur.com/U0HV88U.png

**Comment by mdotstrange** [comment]
> Yes, I have also encountered this same issue and noticed that this usually happens when removing people/toilet options are enabled from the scene option menu.

You found a new bug- thanks maaaan- will fix this- yeh ticking that breaks some scenes

**Comment by mdotstrange** [comment]
Just pushed a new build to Steam _should_ fix the bug/issue when you ticked no people or no toilets with these scenes-

**Comment by mdotstrange** [comment]
> > Just pushed a new build to Steam _should_ fix the bug/issue when you ticked no people or no toilets with these scenes-
> 
> Working perfectly now, thank you!

Hey I'm glad thanks for letting me know-

**Comment by mdotstrange** [comment]
> After loading these scenes everything is blueish black and there is no key response. Requires hard Stop from Steam menu.

Was it the people/toilet issues that you were having? If not, did deleting SavedNightmare resolve the issue?

**Comment by tonikone** [comment]
Scenes load fine now. Checked with and without people/toilets. Did not delete anything.
