### ISSUE TITLE
Click to walk: Walking turns into sliding after couple of steps, then click to walk stops responding.

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#434]
After a series of click to walks actor stops moving towards target and only legs are in motion for a couple of seconds. Both actors are affected.

**Comment by tonikone** [comment]
Scenes seem to behave differently. Emptiness behaves like mentioned above. In Small Pharma Actor keeps sliding towards the targets, without getting stuck into momentary static walk cycle and standing after mouse clicks.

**Comment by mdotstrange** [comment]
Thanks for letting me know- checked and left an important parameter unchecked- will upload fixed build in a few minutes-

**Comment by mdotstrange** [comment]
Bug fix build live on Steam now thanks maaaaaan
