### ISSUE TITLE
Main Menu is super broken

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#438]
Deleted user files after the latest update, still no electric cigar.

https://imgur.com/a/5Kx7062

**Comment by tonikone** [comment]
OK, I can get to whole main menu but buttons don't work..

**Comment by tonikone** [comment]
Deleted Appdata stuff, reinstalled NP, everything is back to fully working weirdness again.

**Comment by mdotstrange** [comment]
Sorry about that- did you save a Player.log file along the way? Would like to see what was causing it

**Comment by mdotstrange** [comment]
Just pushed update should fix this bug
