### ISSUE TITLE
In-game soundfont switching with shift+9 cause NullReferenceExceptions and InvalidOperationExceptions

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#44]
Restarting the app replicates the behavior. Tested with default soundsets only and Ballmouth midi file.

See attached log.

[in-game-soundfont-switching-nullref.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5047282/in-game-soundfont-switching-nullref.txt)

**Comment by tonikone** [comment]
The scene tested was Live Show.

**Comment by tonikone** [comment]
Shift+9 swithing can also cause InvalidOperatorExceptions. Same scene.

See another attached log:

[in-game-soundfont-switching-invalidOperatorException.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5047292/in-game-soundfont-switching-invalidOperatorException.txt)

**Comment by tonikone** [comment]
These happen when switching enough times, so keep on switching to replicate.

**Comment by mdotstrange** [comment]
Thanks for this- checking it out now-

**Comment by mdotstrange** [comment]
The MidiPlayer is third party code- I'll try to fix it- if I can't I'll disable bank switch at runtime

**Comment by mdotstrange** [comment]
Dug into the code- to add all the null checks would have to try and rewrite their code- decided to remove the function- this bug still occurs if you switch the bank really fast in the main menu but that's acceptable because I'm not going to try and rewrite their midi player 0_0- closing this-
