### ISSUE TITLE
Draw an Image for your Scene - froze up program

### ISSUE THREAD

**Issue by RayR10** [mdotstrange/NightmarePuppeteerPublic#444]
Hi,
I'm brand new to NP.  I was going through the settings and I clicked on the Main Menu, Add image to your scene.  Then, I selected first green button with a pencil "Draw an image to use as Image1 in your scene."  Then it just froze up.  I can't get out of it.  I think I'll have to CTRL + ALT + DEL.  Anyone else have this happen?  What was supposed to happen?

Also... I'm a bit disappointing that there is no way to add color to individual body / face parts.  (Painting option.).  I thought that was a cool feature and a quick way to customize a character.... but looks like it was removed.  :( 

![Screenshot 2024-06-16 130225](https://github.com/mdotstrange/NightmarePuppeteerPublic/assets/172993710/2bb40274-ee0e-4112-9623-bdc7ad3d169c)

**Comment by mdotstrange** [comment]
Hello- that should be working so this is a bug- I will check it out tonight- sorry and thanks for letting me know about it.

**Comment by mdotstrange** [comment]
Updated the build with a fix for this- thanks for letting me know about it.

**Comment by RayR10** [comment]
No problem.  I'm a good bug finder.  Actually... bugs are attracted to me!  Thanks for looking into that.  I appreciate it.

**Comment by RayR10** [comment]
Just giving you a confirmation that both the "draw an image" and upload image are working now.  Thank you. 

![Screenshot 2024-07-05 222603](https://github.com/mdotstrange/NightmarePuppeteerPublic/assets/172993710/098dbf6e-5c68-44a8-b9f1-ffcdf15be2ce)
