### ISSUE TITLE
Main menu: MIDI file name disappears after relaunching the app

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#45]
MIDI file is still present and playable OK in the scene.

Produced by:

1. Start app.
2. Load MIDI file
3. Start scene.
4. Exit to Main Menu, exit app.
5. Relaunch app

See pictures. First is after Loading MIDI file. The second is after relaunching app (5). Notice how audio playlist file name disappears too, connected to issue #4.

https://imgur.com/a/Iu9fMTC

**Comment by mdotstrange** [comment]
Fixed this one and the Audio playlist file name missing as well- thanks!
