### ISSUE TITLE
Suggestion for Menu buttons and manipulators: Add a fixed text line tooltip in the GUI informing what an item does.

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#47]
While hovering over an icon or other clickable item, one could see a fixed line of text updating in the lower edge of menu pages with a short description of what an item does. This would lessen the need to consult separate manual when one sees icons/sliders without text description for the first time, and is a fast overall reminder of what does what.

**Comment by mdotstrange** [comment]
Ah great idea! Will do this- thanks!

**Comment by mdotstrange** [comment]
Added this- will be in next build update-

**Comment by mdotstrange** [comment]
Uploading new build with this in it to Steam in a bit- Thanks for the suggestion!- closing this
