### ISSUE TITLE
Subtitles: NullReferenceError on .srt end (Scene time)

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#49]
Passing last title triggers NullReferenceError on scene time.

Attaching log file:

[output_log_nullRef_on_srt_end.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5051270/output_log_nullRef_on_srt_end.txt)

.srt can't be attached, here it is:

***
1
00:00:00,000 --> 00:00:05,000
Title one

2
00:00:05,000 --> 00:00:10,000
Hey it's title 2

3
00:00:10,000 --> 00:00:15,000
Third one, maaan

4
00:00:15,000 --> 00:00:20,000
Fourth title, still one to go

5
00:00:20,000 --> 00:00:25,000
Last Title, WAIT FOR THE ERROR A BIT
***
File ends

**Comment by mdotstrange** [comment]
Added a null check to avoid the error and used your sample file- it played for a few minutes after the last title with no error- so going to say this is closed- thanks!
