### ISSUE TITLE
Feature request : Option to stop unselected Buddy to stop wandering around

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#5]
Changing actors with F9 causes the unselected/unseated actor to start wandering around. This makes setting up static two camera OTS dialogue shots cumbersome among other things. An option for unselected actor to stay put would help.

Making a short loop for the buddy could be a workaround for now.

**Comment by mdotstrange** [comment]
I can make it so you can toggle their state machine which causes the walking around etc

**Comment by mdotstrange** [comment]
Added a Buddy Random Walk toggle in the Options menu + a Keyboard shortcut to Toggle it at runtime- thanks!
