### ISSUE TITLE
Subtitles: Titles still play after Clear Subtitle button used

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#50]
After clearing a loaded subtitle file with Clear Subtitle button and launching into the scene, the subtitle still starts playing.

Attached Log:

[output_log_subtitle_clear_button_has_no_effect.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5051481/output_log_subtitle_clear_button_has_no_effect.txt)

**Comment by mdotstrange** [comment]
They weren't being cleared properly- fixed and tested- closing this- thanks!
