### ISSUE TITLE
unsure how workshop integration works/ workshop tool tips

### ISSUE THREAD

**Issue by spooktergeist** [mdotstrange/NightmarePuppeteerPublic#52]
I was able to export a character DNA to the workshop with a thumbnail and description. But i do not know how to import a character from the workshop into NP. I was able  to save and load the 3 DNA preset slots but haven't figured out how to get a workshop character into the scene.

also the workshop window on the main menu could use some tool tips as well

**Comment by mdotstrange** [comment]
Thanks for this- yeh right now the only way to get stuff from Workshop is by the big Steam icon on the right side of the Main menu- going to add more ways- thanks!

**Comment by mdotstrange** [comment]
Working on this now- making it WAY easier to use-
