### ISSUE TITLE
Main menu: Hitting play on MIDI does not produce a preview sound

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#6]
Is there special Windows 10 requirements for MIDI playback to work?

**Comment by mdotstrange** [comment]
Was a midi file loaded using the Load Midi button? I think the sound bank file name in green could be mistaken for a loaded midi file-

**Comment by mdotstrange** [comment]
Added details in the manual to addressing what plays what

**Comment by tonikone** [comment]
Good, I thought presence of soundfonts indicated presence of a playable MIDI file too.

**Comment by mdotstrange** [comment]
Sorry for the mix it- its s bad design- will look at re-factoring it later
