### ISSUE TITLE
Actor switching in scene influences switches actor order in main menu

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#64]
Noticed this while working in House on Fire scene.

To replicate:
1. Switch to buddy wtih F9. Exit to main menu. Actor placement in the menu has now switched. Loading DNA can lead to confusion, if one set up specific DNA slots for an individual actor. And what really gets reset if one now presses actor reset in the main menu?

**Comment by mdotstrange** [comment]
What would be a preferred situation? At the end of a scene make sure the Main actor that started the scene is the main actor etc?

**Comment by mdotstrange** [comment]
Added some code so the actor roles that started the scene remain when the scene ends-

**Comment by mdotstrange** [comment]
Fixed and tested this- actor roles are consistent- thanks!
