### ISSUE TITLE
Audio playlist upload/download to Steam Workshop untested-

### ISSUE THREAD

**Issue by mdotstrange** [mdotstrange/NightmarePuppeteerPublic#65]
needs to be tested to make sure they load correctly and refresh the playlist on download

**Comment by tonikone** [comment]
I uploaded a list with a single item in it. It works, file starts playing in main menu, but list is not updated. The download buttons, checkmarks, etc. have no text on them, some clarification needed there on what does what.

One list upload was stopped with "upload over 10 MB". Question arose: What was capped? Single file, all files, what? What are max upload counts, if any (for zillion small files?), user space on workshop (upgradeable? limitless?), cooldown times? Those could be probed (if possible) and communicated in the app before uploading something that will get aborted.

**Comment by mdotstrange** [comment]
Thanks for testing it- I'll try and fix these things today- yeh thats weird about the upload size as I've uploaded audio files 50 mb+ to workshop- I did some reading and seems Steam Workshop has random bugs like that popup sometimes-

**Comment by mdotstrange** [comment]
Working on this- strange though when I open the Workshop window to download Playlists I only see the one I added, I don't see yours yet when I check on the Workshop site I see yours and it has the correct tag, the same as mine- it should be visible 0_0

**Comment by mdotstrange** [comment]
Hey Tony- did you set your recent workshop uploads to "Friends Only" manually or is that a bug I need to look at? I noticed it trying to figure out why some Workshop uploads I can see as moderator do not show up in the workshop download window.

**Comment by tonikone** [comment]
Ignore what I said earlier, I make things a bit clearer: If I push Steam Download Playlist button on start menu and download playlists, the playlist items are added to playlist (still have to go to playlist page and to verify the list is updated). On the playlist page I can preview the files by clicking list items and pressing play. However, when I exit the playlist page to main menu, pressing play to preview actor audio does not function. Then, in the scene the files play back. After exiting the scene the actor audio preview buttons work again. 

If I press the Steam download button in the _playlist_ window and do the adding there nothing gets added to list, nothing plays on main menu audio preview button, and nothing plays in the scene while tabbing.

Items seen in these two Steam download dialogs are different. I can't get into all my subscriptions from the main menu steam playlist download button. When pressing download steam playlist button on the playlist page I see my subscriptions.

**Comment by mdotstrange** [comment]
Updated the Build on Steam just now- Give that one a try though it might not work with previously uploaded items. Also I asked in a few places but guess you didn't see it- I noticed some of your items are listed as "Friends only" so they can't be accessed by others- is that a bug I should look into or did you set it manually? If so, how? Thanks!

**Comment by tonikone** [comment]
Visibility problem is gone now, after putting sufficient funds to Steam (enables Public Visibility option). I've put out new issues before writing this post. #78 is the latest, so check the new issues out. #74 showstopper warning!

**Comment by mdotstrange** [comment]
Thank you for testing this!
