### ISSUE TITLE
Control + Click Look At head rotation is passed to newly selected buddy when switching.

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#7]
To reproduce:

Use Control + Click Look At. Press F9. The Head rotation is copied to newly selected Buddy. After switching the rotation cannot be cleared. To do this, one must switch back to original actor and reset there.

**Comment by mdotstrange** [comment]
Re-factored the "look at" stuff- got rid of that bug and now the "look at" transitions are all smooth + when switching actors they retain their look at position- thanks!
