### ISSUE TITLE
Scenes do not respond to key presses

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#74]
Tested with Elevator Pitch and Nothingness. All keyboard activity has vanished, including the Esc and Enter key. Is this related to adding new action sets?

**Comment by mdotstrange** [comment]
Tried to reproduce this and couldn't- can you send your debug log? I just launched the game from Steam, tried the scenes you mentioned and a few others and I was able to use key presses including Return and Escape-

**Comment by mdotstrange** [comment]
So the Midi error was really an audio error- working on the audio thing now as if you loaded a lot of audio files would eventually eat all your memory causing OOM error which you got- might have broken everything else as there was no memory available until quit-

**Comment by tonikone** [comment]
The new build fixes keyboard in the scene, MIDI files playback fine, and now using shorter audio files for testing, deleted my big file list from Workshop. If you can also probe for too big audio files besides warning in writing, that would be ideal. Leaving OOM hanging could cause trouble. Read the file size, don't start loading (and uploading) too big stuff and make it known in the GUI.

**Comment by mdotstrange** [comment]
Great idea- yeh I need to check the file size- will add to tomorrows build- uploaded a new build just now as I was getting out of memory errors with normal audio files from some changes I made-

**Comment by mdotstrange** [comment]
Isssue fixed as was result of another error that has been resolved-
