### ISSUE TITLE
Warning: Workshop loaded MIDI files don't carry over to new builds.

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#76]
While testing the newest build (is there an in-game version number or does Steam has the info for developers?) I got an OutOfMemoryError after pressing MIDI playback button in Main Menu.

Reloading the MIDI file with Workshop add button cured this, and the setting is kept through app restart.

Log:

[output_log_MIDI_playback_out_of_memory_error.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5074648/output_log_MIDI_playback_out_of_memory_error.txt)

**Comment by mdotstrange** [comment]
Looking at the error- error occurred in the third party code that loads audio files into the audio playlist- looks like it happened when the audio recorder window was opened

**Comment by mdotstrange** [comment]
So any audio file that was loaded in a menu was never released from memory until you loaded a scene- so if a user experimented with loading several audio files into voice slots/playlists etc it would eventually take up all the memory on the machine 0_0 Now the menu is constantly unloading un-used assets so this shouldn't occur- I'm going to add a warning on the playlist though as you could fill the memory if you load in 18 really long audio files-

**Comment by mdotstrange** [comment]
Look at the midi/saving from Workshop and it looked like it did save it but it didn't show the file name- I made some changes for that-

**Comment by mdotstrange** [comment]
Closing this- thanks!
