### ISSUE TITLE
Main menu: Actor1 voice Main Menu playback button does not work  

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#78]
Previewing list items works in the list editor, but when coming back to Main Menu, Actor1 play button does not preview the sound item. Buddy play button works OK, playing back the first item in the list.

**Comment by mdotstrange** [comment]
Tried to reproduce this and couldn't- can you describe the steps? I went into Main actor audio playlist, recorded a clip then tried to play it back in the main menu and it played-

**Comment by tonikone** [comment]
Exit the app and relaunch, press the button. Forgot to talk about that, sorry!

**Comment by tonikone** [comment]
Relaunching the app also swipes the audio file name from the Actor1 record/playlist button, leaving three dots remaining. Scene tabbing works fine now that I got my file sizes sorted out.

**Comment by mdotstrange** [comment]
Is this still an issue in the newest build?

**Comment by tonikone** [comment]
Uh oh. NullRefException on Workshop playlist download. The playlist (TestingPlaylist, "Ees a test!") items don't appear in the playlist.

Log:
[output_log_playlist_workshop_download.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5123280/output_log_playlist_workshop_download.txt)

**Comment by tonikone** [comment]
Weirdness: After this, loading one audio file through file dialog, the item is replicated three times in the playlist. That is the count of files in TestingPlaylist I used earlier.

**Comment by tonikone** [comment]
... X:ing one playlist item deletes all replicated playlist items. Might try reloading the app and going straight file system dialog import..

**Comment by tonikone** [comment]
... NullRefException also there.

Log:
[output_log_playlist_file_dialog_import.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5123340/output_log_playlist_file_dialog_import.txt)

**Comment by mdotstrange** [comment]
Fixed the null refs- now working on the duplicate file issue

**Comment by mdotstrange** [comment]
Fixed the duplicate file issue- Will upload new build today-will be Beta 2.3- needs more testing though- thanks

**Comment by mdotstrange** [comment]
Playback buttons all work correctly now after changes- closing this- thanks!
