### ISSUE TITLE
Warning: Alt+Tab is assigned to Win10 window switching

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#80]
This might not work at least in windowed mode if Unity can't turn off global Windows shortcuts. I can't test it fully now, because of #74.

**Comment by mdotstrange** [comment]
Will change this shortcut- thanks!

**Comment by mdotstrange** [comment]
Changed the shortcut to Hold Middle Mouse Click + Tab- updated manual + controls page- closing this- thanks!
