### ISSUE TITLE
Level editor special items mentioned in the manual can't be found in the editor item icon view

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#81]
I can't find Start point of actors and other special items mentioned in the manual. Where are they?

**Comment by mdotstrange** [comment]
They are all at the very top of the icons
Here are the Start points https://i.imgur.com/6BTmxDb.png
The camera https://i.imgur.com/enqugAJ.png
The light https://i.imgur.com/lGi2BX8.png
The green screen https://i.imgur.com/5TjKvgz.png
The dunk tank has an invisible icon for reasons I don't understand as do a few others 0_0 Its the blank icon to the left of the green screen-

The icon generation is 3rd party code --> https://github.com/yasirkula/UnityRuntimePreviewGenerator

Yeh some are blank, tried to mitigate it but couldn't get it working hence its called Lousy haha

**Comment by tonikone** [comment]
Weird. I deleted appdata files, steam files, reinstalled and those icons are not there. What is going on?

Pix:
https://imgur.com/a/A1qB1Ue

**Comment by mdotstrange** [comment]
I think I know what's happening- due to the editor being lousy if you drag the bar on the side it only shows two rows- you have to click drag the icons themselves and it pulls the window down to show more- I'll fix that or add instructions

**Comment by tonikone** [comment]
Holy Mackerel, I can see everything! Instruction mention of click drag for now, definitely.

**Comment by mdotstrange** [comment]
I'm trying to fix the scrollbar but Unity UI stuff is confusing to me 0_0 If I can't fix it will add instruction.

**Comment by mdotstrange** [comment]
Ok I fixed it- scrollbar is now the correct size so you can scroll the whole way and used an arrow as handle to relay then you scroll down now to access more
https://i.imgur.com/OFNVWHY.png

**Comment by mdotstrange** [comment]
New build on Steam that fixes this- thanks!
