### ISSUE TITLE
Per actor voice activation does not work in Scene dialog playback

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#82]
1. Activate buddy. Load audio playlist items for both actors.
2. Start scene. Issue 1 (Minor one). Dialog playback for buddy starts automatically. Is this correct behaviour?
3. Tab to play Actor1 playlist items. Works fine.
4. F9 to switch to buddy.
5. Tab to play buddy playlist items. Issue 2 (Bug). Tab keeps playing Actor1 playlist items as buddy voice.

**Comment by mdotstrange** [comment]
Forgot to test that! Will fix in tomorrows build

**Comment by mdotstrange** [comment]
Started work late today so will probably be in a build tomorrow but starting on it now-

**Comment by mdotstrange** [comment]
Just fixed this one- good find maaaan! Thanks!
