### ISSUE TITLE
Main menu: Moving MIDI playback speed slider produces NullReferenceError

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#84]
Reproduce:

MIDI file (Toccata by Bach) was loaded in some earlier session. Then build was updated to newest.
1. Start app
2. Move the MIDI playback speed slider. NullRef is triggered.

Log:

[output_log_main_main_midi_slider_nullReferenceException.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5078436/output_log_main_main_midi_slider_nullReferenceException.txt)

**Comment by tonikone** [comment]
Going further and reloading the Workshop item TestBach seems to fix this. No more triggered NullRefs.

**Comment by mdotstrange** [comment]
I've gotten this one before- so with this one occurs randomly when changing midi tempo while playing- as far as I can see the errors don't break anything so when debug mode is disable they'll have no effect- digging into the 3rd party code I added all the null checks I could without trying to rewrite the code- so its keep feature with seemingly harmless errors or remove it.

**Comment by mdotstrange** [comment]
Did my best to resolve this- still pops up but doesn't do any harm- when NP is released it won't be a dev build so users won't see the error- closing this- thanks!
