### ISSUE TITLE
Head prop editor: Nose and hair are instanced on space+click and move, can't be cleared

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#87]
1. Go to head editor
2. Space+click to select hair/nose, select move 3D manipulator. To see the bug more clearly, move the item well above the head.
3. Use next/previous arrows for the item. A new item is now present on the head with the original item, sometimes small, use size slider to see more clearly.
4. Now hair items can be cleared with cross, except the original item. Duplicate nose items can't be cleared.

**Comment by mdotstrange** [comment]
Did some work on this- the instances should be gone now-  still needs testing though-

**Comment by mdotstrange** [comment]
Just submitted a new build with changes for this and the anim freeze w vlooper issue

**Comment by tonikone** [comment]
Tested hair and nose props. Looking good.

**Comment by mdotstrange** [comment]
Closing this- thanks!
