### ISSUE TITLE
[Feature request] Ability to rotate actors and props in menu's

### ISSUE THREAD

**Issue by mdotstrange** [mdotstrange/NightmarePuppeteerPublic#9]
From tester Vae

**Comment by tonikone** [comment]
Global actor rotation without walking would be nice. Sometimes walking to rotate destroys my carefully constructed auteur framings.

Advanced actor preview in menu could have a catwalk of shiftable slice of actors who do 360. Animated full body police mugshot animated gifs might do the thing too. A hybrid of scrollable images and a 3D model in the middle could be a thing too.

**Comment by mdotstrange** [comment]
Ah I'll see if I can add the actor rotate to the control I'm adding now- I've added the BuddyRandomWalk toggle which also disables them looking in directions as well so that can also help that issue-

**Comment by mdotstrange** [comment]
Add the same controls the Lousy Level Editor uses for the Edit Actor and Edit Head Menu's- can now move camera around and select props manually to change their position/scale/rotation- moving the position is really flaky but rotation and scale work fine- closing this--

**Comment by tonikone** [comment]
>  I can add the actor rota..

Uhum, I noticed also there is a shortcut for scene actor rotation, the period. The Puppet Wave Auteur here must learn to read da manual..

ALT + period could switch the direction of rotation, but don't put that too high on the feature list. Every key counts.
