### ISSUE TITLE
Unresponsiveness

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#91]
Game became unresponsive  and triggered the Windows "close this program" alert  twice:

* After vanity cards/before language selection.
*  **VERY IMPORTANT** During the load screen after language selection right after the loading bar is complete. This unresponsiveness took almost two minutes to go back to normal.

**Comment by mdotstrange** [comment]
Have seen freezes of a few seconds but not that long- How much Ram does your system have and what type of hard drive is the game installed on? Sata/ssd/m2? Thanks for the report!

**Comment by weevilgit** [comment]
SATA and 8GB of ram.

**Comment by mdotstrange** [comment]
The older builds were slower than the newer ones when it comes to loading- but I think with a Sata and 8gb's might still be slowish- recommended specs are SSd/m2 and 32 gig a ram-

Is this still an issue in the newest build? On my system (SSD, 32gb ram) it hangs for about 6 seconds with the current build-

**Comment by mdotstrange** [comment]
Switched the build over to 64 bit which makes loading faster and further optimized some things to speed loading up but even with recommended specs there is a few second hiccup. On a system with minimum specs and under expect longer stalls/loading times. Sorry about that-
