### ISSUE TITLE
UI: Loading screen unclear for first-timers

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#92]
![R01](https://user-images.githubusercontent.com/69782583/90374810-71d1d480-e04a-11ea-91cb-9ae18aff30d4.jpg)

For first-timers, this bar looks like a black square with half of the letter "A" for several seconds. It's unclear if it's loading or not.

Suggestions: Either include an empty or grayscale bar underneath it to indicate what 100% would be or replace it with a rotating icon that doesn't indicate any percentages whatsoever.

**Comment by mdotstrange** [comment]
Ah good idea! I'll add a spinny loading thing there- thanks!

**Comment by mdotstrange** [comment]
I've animated animated spinning loader elements and a blinking "loading..." text above the bar- thanks!
