### ISSUE TITLE
UI: Letter G looks like an "8"

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#93]
![R01](https://user-images.githubusercontent.com/69782583/90375373-3e437a00-e04b-11ea-958b-a4af3b4d1416.jpg)

The letter G looks like the number 8 in this font at this size.

**Comment by mdotstrange** [comment]
Added spinning gears and "Loading.." text so users are not confused as to what is happening- closing this- thanks!
