### ISSUE TITLE
UI: Main menu buttons are mostly unclickable

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#94]
![UI02](https://user-images.githubusercontent.com/69782583/90375503-6df28200-e04b-11ea-9feb-c53d90c8adfc.jpg)

The green boxes in the image above represent the portions of the buttons that respond when clicked. In some of those items, most of the text is unclickable.

**Comment by mdotstrange** [comment]
Fixed this- thanks!
