### ISSUE TITLE
UI: Small fonts are unreadable in small resolutions

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#95]
![UI03](https://user-images.githubusercontent.com/69782583/90375788-cf1a5580-e04b-11ea-9d02-59f1e8176a3d.jpg)

The issue is especially problematic with the green tooltip, which is unreadable even in 720p (windowed, not upscaled). The other texts also start to become difficult to read in this resolution.

**Comment by mdotstrange** [comment]
The new Ui has bigger text and the recommended resolution is 1920 x 1080- closing this- thanks
