### ISSUE TITLE
UI: About 20% of the screen is invisible when the window is maximized

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#96]
![UI05](https://user-images.githubusercontent.com/69782583/90376169-667fa880-e04c-11ea-8659-70850dc31111.jpg)

**VERY IMPORTANT:** The green tooltip is invisible.

**Comment by mdotstrange** [comment]
Is this windowed or full screen mode? And at what resolution? Thanks!

**Comment by weevilgit** [comment]
Windowed. The window is maximized, 720p.

**Comment by mdotstrange** [comment]
Is this still an issue with the new Ui?

**Comment by weevilgit** [comment]
Yeah, still getting it.

**Comment by mdotstrange** [comment]
Full Screen or windowed? And what resolution are you running at?

**Comment by mdotstrange** [comment]
The recommended resolution is 1920 x 1080. I just ran the game at 720p (Not in windowed mode) and it looks like this- nothing seems to be cutoff https://i.imgur.com/ZXTdqxj.jpeg
