### ISSUE TITLE
FEATURE REQUEST: Make "Tutorials" button warn that it opens the browser

### ISSUE THREAD

**Issue by weevilgit** [mdotstrange/NightmarePuppeteerPublic#99]
Alternatively: Open steam internal browser, which is much lighter than an external browser.

Rationale: I have a PC with limited ram (8GB), clicking the button almost froze my computer the first time I did it (as a side note: I'm convinced Samsung hired Stevie Wonder to write their system code. and that he was drunk during the whole ordeal.)

**Comment by mdotstrange** [comment]
Didn't even know there was a Steam internal Browser- I will look into it- thanks!

**Comment by weevilgit** [comment]
You can access it with the [Steam Overlay](https://partner.steamgames.com/doc/features/overlay). The shortcut is Shift+TAB while the game is playing.

**Comment by mdotstrange** [comment]
Looking at the Steam APi and found [this ](https://partner.steamgames.com/doc/api/ISteamFriends#ActivateGameOverlayToWebPage)

I'm using the C# Steamworks wrapper and looking through the methods and callbacks + googling I find nothing on how to do this 0_0

**Comment by weevilgit** [comment]
I believe [this is the API call](https://partner.steamgames.com/doc/api/ISteamFriends#ActivateGameOverlayToWebPage), I`m not familiar with the library you're using, would you link the documentation so I can take a look?

**Comment by mdotstrange** [comment]
Yes I know, I posted that Api call in the reply above yours in the linked text "this" ^_^ Steamworks documentation is very limited and it is not in there. https://github.com/rlabrecque/Steamworks.NET. I'm not using FacePunch studio's Steamworks C# wrapper but it has a very good help so I've been looking through the FacePunch help to get a better idea of that to call etc- I'll take a look again when I get a chance.

**Comment by weevilgit** [comment]
Oh, I apologize. For some reason I didn't pay attention to the url you referenced.

See if this works (from lines 287-296 in [Plugins/Steamworks.NET/autogen/isteamfriends.cs](https://github.com/rlabrecque/Steamworks.NET/blob/1cad640a21c2819c9fc95f397e1fb11f36e11fcb/Plugins/Steamworks.NET/autogen/isteamfriends.cs)):


```
                /// <summary>
		/// <para> activates game overlay web browser directly to the specified URL</para>
		/// <para> full address with protocol type is required, e.g. http://www.steamgames.com/</para>
		/// </summary>
		public static void ActivateGameOverlayToWebPage(string pchURL, EActivateGameOverlayToWebPageMode eMode = EActivateGameOverlayToWebPageMode.k_EActivateGameOverlayToWebPageMode_Default) {
			InteropHelp.TestIfAvailableClient();
			using (var pchURL2 = new InteropHelp.UTF8StringHandle(pchURL)) {
				NativeMethods.ISteamFriends_ActivateGameOverlayToWebPage(CSteamAPIContext.GetSteamFriends(), pchURL2, eMode);
			}
		}
```

**Comment by mdotstrange** [comment]
Ah thanks! I'll give it a try!

**Comment by mdotstrange** [comment]
Hmmm 2 parts of it are inaccessible due to calling an Internal class - 
https://i.imgur.com/Gt9GVwg.png
Do you know how to call methods on internal classes? I'm afraid of making them public as it might implode my personal Steam universe of something ^_^

**Comment by mdotstrange** [comment]
That must have been the old way to do it- thanks to your post I found it
https://i.imgur.com/yc3W6lB.png
Thanks again!

**Comment by mdotstrange** [comment]
If Steam is connected the Tutorial window now opens in the Steam Browser https://i.imgur.com/oncZnJS.png

Thank you for your help!- Closing this
